### ISSUE TITLE
Does copy-and-paste reverse-engeener entities intended to work?

### ISSUE THREAD

**Issue by slavb18** [jeddict/jeddict#242] opened 2017-09-13 05:48 UTC
Hi!

Does copy-and-paste reverse-engeener entities intended to work?

Tryed in jeddict 4.4.1 entity class drag and drop from projects panel to model, copy and paste,
and no errors and nothing done.

**Comment by jGauravGupta** [comment] 2017-09-13 18:49
This is cool feature but not yet supported.

Duplicate of :  #133  & #195

**Closed by jGauravGupta** 2017-09-13 18:49 UTC

**Comment by slavb18** [comment] 2017-09-14 04:16
thanks, sorry
