### ISSUE TITLE
@Enumerated(EnumType.STRING) is generated as @Enumerated("EnumType.STRING")

### ISSUE THREAD

**Issue by skonx** [jeddict/jeddict#363] opened 2019-11-26 18:00 UTC
Hi.

Enumerated annotations are translated with a String.
Same behaviour with other annotations (like @Inheritancec annotation for example).

##### **Jeddict Version(s)**

5.3 on Netbeans 11.1

**Comment by skonx** [comment] 2019-11-26 18:02
workaround : add the annotation on the field/property and add required imports in the snippets

**Comment by jGauravGupta** [comment] 2019-12-08 07:20
Duplicate of https://github.com/jeddict/jeddict/issues/339

**Closed** 2019-12-08 07:45 UTC
Labels: bug :bug:
