### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ShannieCh** [jeddict/jeddict#256] opened 2017-12-12 14:19 UTC

**Comment by Chris2011** [comment] 2017-12-12 14:33
No bug?

**Comment by annaflyer** [comment] 2017-12-13 12:04
Yes, I agree ;)

**Comment by ShannieCh** [comment] 2017-12-13 12:08
Using NetNeans IDE 8.1 instead of NetBeans IDE 8.2 solved the problem

**Comment by Chris2011** [comment] 2017-12-13 12:09
So please close it. Thx.

**Closed** 2017-12-13 12:10 UTC

**Comment by Chris2011** [comment] 2017-12-13 12:11
It would be good to know the problem anyway, because no one can fix it, if no one is requesting it in NB 8.2. So your help is much needed to make reproducable steps to find the bug in NB 8.2. Thx :)
